# Generated by Django 6.0 on 2025-12-12 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergoal',
            name='goal_type',
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='target_weight',
        ),
        migrations.AddField(
            model_name='usergoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergoal',
            name='current_weight',
            field=models.FloatField(default='2025-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergoal',
            name='diet_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.dietplan'),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='duration',
            field=models.IntegerField(default='2025-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergoal',
            name='height',
            field=models.FloatField(default='2025-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergoal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Plan Assigned')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='target_gain',
            field=models.FloatField(default='2025-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergoal',
            name='workout_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.workoutplan'),
        ),
    ]
