# Generated by Django 6.0 on 2025-12-21 06:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_usergoal_goal_type_remove_usergoal_start_date_and_more'),
    ]

    operations = [
        # If current_weight does not exist, we add target_weight directly
        migrations.AddField(
            model_name='usergoal',
            name='target_weight',
            field=models.FloatField(default=0.0),  # numeric default
            preserve_default=False,
        ),

        # Remove old fields safely (if they exist)
        migrations.RemoveField(
            model_name='usergoal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='diet_plan',
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='height',
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='target_gain',
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='workout_plan',
        ),

        # Add goal_type correctly
        migrations.AddField(
            model_name='usergoal',
            name='goal_type',
            field=models.CharField(
                choices=[('gain', 'Weight Gain'), ('loss', 'Weight Loss')],
                max_length=10,
                default='gain'  # valid default value for CharField
            ),
            preserve_default=False,
        ),

        # Add start_date correctly
        migrations.AddField(
            model_name='usergoal',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),

        # Update other fields
        migrations.AlterField(
            model_name='dietplan',
            name='meals',
            field=models.TextField(help_text='Breakfast, lunch, dinner'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='medical_issue',
            field=models.TextField(blank=True, null=True),
        ),
    ]
