# Generated by Django 6.0 on 2025-12-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_current_weight_usergoal_target_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergoal',
            name='current_weight',
        ),
    ]
