# Generated by Django 6.0 on 2025-12-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_usergoal_current_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoal',
            name='current_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='diet_type',
            field=models.CharField(blank=True, choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian'), ('vegan', 'Vegan')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='duration_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='target_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
