# Generated by Django 6.0 on 2025-12-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_usergoal_current_weight_usergoal_diet_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergoal',
            name='goal_type',
        ),
    ]
