# Generated by Django 6.0 on 2025-12-21 17:02

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_usergoal_goal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoal',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=datetime.date.today),
            preserve_default=False,
        ),
    ]
